### ISSUE TITLE
Problem on run SpeechNote

### ISSUE THREAD

**Issue by avex48** [flathub/net.mkiol.SpeechNote#46]
Hi, I'm an old IT enthusiast, not very expert. My system is a minimal installation of Void Linux with OpenBox and Spacefm, set up by a friend of mine.
I have this problem: when I launch SpeechNote I get these errors:

/dev/shm $ flatpak run net.mkiol.SpeechNote
ERROR: ld.so: object '/usr/lib/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ALSA lib ../../oss/pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib ../../pulse/pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connessione rifiutata

ALSA lib ../../pulse/pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Connessione rifiutata

ALSA lib ../../../src/pcm/pcm_direct.c:2045:(snd1_pcm_direct_parse_open_conf) The field ipc_gid must be a valid group (create group audio)
ERROR: ld.so: object '/usr/lib/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/usr/lib/libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

What can I do? Thank you.

**Comment by avex48** [comment]
Sorry I meant: Hi,  I'm an old IT enthusiast, not very expert. My system is a minimal installation of Void Linux with OpenBox and Spacefm, set up by a friend of mine.
I have this problem: when I launch SpeechNote I get these errors:
.....
Thank you, thank you.

**Comment by mkiol** [comment]
Thank you for the report.

To have more verbose logs, could you please run the app with `--verbose` option?

```
flatpak run net.mkiol.SpeechNote --verbose
```

**Comment by avex48** [comment]
Thanks for the support. Here is the log:
[SpeechNote-log.txt](https://github.com/flathub/net.mkiol.SpeechNote/files/14294048/SpeechNote-log.txt)

Thanks again.

**Comment by mkiol** [comment]
For some reason the app hangs in PyTorch CUDA check. It should just report an error but it hanged. I have no idea why 🤔.

```
[D] 10:09:32.924 0x7faa13e00600 libs_availability:61 - checking: torch cuda
```

You can disable any Python components with `--py-scan-off` option. This might help. Please, check if app is able to start with that option. 

```
flatpak run net.mkiol.SpeechNote --verbose --py-scan-off
```

If this is successful, the functionality of the application will be slightly limited, but you will be able to use most of the functions. You don't have to use `--py-scan-off` every time. Start the app with this option only once. You can re-enabled Python in the settings (Settings->Other->Libraries->Check Python dependencies)

Alternatively to `--py-scan-off` , if you have NVIDIA or AMD graphic card, you might try to install Speech Note Add-on which provides CUDA or ROCm libraries for GPU acceleration. It might help as well.

```
flatpak install net.mkiol.SpeechNote.Addon.nvidia
```

or 

```
flatpak install net.mkiol.SpeechNote.Addon.amd
```

**Comment by avex48** [comment]
Good morning and thanks for your help.
I installed the Nvidia video card module with this command:

flatpak install net.mkiol.SpeechNo
![SpeechNoteImage](https://github.com/flathub/net.mkiol.SpeechNote/assets/35814290/1719ef63-f5bd-46a6-9b00-1c328e9854c8)
[SpeechNote-log.txt](https://github.com/flathub/net.mkiol.SpeechNote/files/14297892/SpeechNote-log.txt)
te.Addon.nvidia

Launching SpeechNote (with --verbose) produces the attached log and in the image "SpeechNoteImage.png" the situation I find myself in.

What I do? Thank you.

**Comment by avex48** [comment]
Everything seems to work!

I have now installed the templates for translation, punctuation and for the "Speech to Text" function.

Do you need a microphone? I have a Windows Webcam, is that OK?

Thank you.

**Comment by mkiol** [comment]
I'm glad it helped.

App didn't detect any supported NVIDIA graphic cards, but still you can use everything without GPU acceleration. Just speech-to-text will be much slower. 

What is your graphic card?

> Do you need a microphone? I have a Windows Webcam, is that OK?

Yes, but only when your webcam has microphone built-in :) You can change "Audio Source" in the settings.

**Comment by avex48** [comment]
My graphics card is a "GeForce GTX 970".
These are my audio settings:

Audio:
  Device-1: Intel 7 Series/C216 Family High Definition Audio vendor: Lenovo
    driver: snd_hda_intel v: kernel bus-ID: 00:1b.0
  Device-2: NVIDIA GM204 High Definition Audio vendor: Gigabyte
    driver: snd_hda_intel v: kernel bus-ID: 01:00.1
  API: ALSA v: k6.7.4_1 status: kernel-api
  Server-1: PulseAudio v: 16.1 status: active

You say: "You can change "Audio Source" in the settings."

What do I need to change?

A thousand thanks!

**Comment by mkiol** [comment]
> What do I need to change?

No, you don't need to change it. I mentioned this option in case you have more than one microphone and want to choose a specific one. When "Auto" is set, the default microphone in your system is used.

> My graphics card is a "GeForce GTX 970".

Unfortunately you card is not supported in CUDA 12. This is a reason why is not detected.

BTW, this repository is only for Flatpak build. If you would like to report anything more, the best place to submit an issue is this project https://github.com/mkiol/dsnote.

**Comment by mkiol** [comment]
Closing this old issue report.
