### ISSUE TITLE
Speech Note instantly crashes when opened.

### ISSUE THREAD

**Issue by nPrevail** [flathub/net.mkiol.SpeechNote#50]
I've installed speech note on other desktops, with the same configuration and distro, but with different Desktop Environments: KDE Plasma and GNOME. 

Speech Note crashes when I use KDE Plasma 5.27 as my DE. On GNOME, Speech Note seems to work perfectly fine. I've tried Plasma and Speech note on two different desktops, and they both crash. GNOME doesn't seem to have an issue with Speech Note.

**Comment by mkiol** [comment]
Thanks for the report. Let's track the problem in https://github.com/mkiol/dsnote/issues/132.
